config/routes.rb
SwaggerRails::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure', :as => :auth_failure
  match '/auth/facebook', :as => :facebook_login

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy", :as => :user_logout
  end

  devise_for :users


  constraints(ForeignDomain::Route) do
    root :to => "docs#show"
    get "/:name", :controller => "resources", :action => 'show'
  end
  
  root :to => 'admin/docs#index'

  namespace :admin do
    root :to => "docs#index"
    resources :docs do
      resources :models
      resources :resources do
        resources :apis
      end
    end
  end
end

app/models/api.rb
class Api < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :resource
  delegate :doc, :to => :resource
  has_many :parameters, :dependent => :destroy
  accepts_nested_attributes_for :parameters, :allow_destroy => true
  has_many :error_responses, :dependent => :destroy
  accepts_nested_attributes_for :error_responses, :allow_destroy => true
  validates_presence_of :path
  validates_presence_of :resource_id
  validates_presence_of :doc_id
  validates_presence_of :http_method
  validates_uniqueness_of :path, :scope => [:doc_id, :http_method]
  HTTP_METHODS = [:GET, :POST, :PUT, :DELETE]

  before_validation :sync_doc_id

  include ActsAsSortable

  def to_json
    { 
      :path => path,
      :description => resource.description,
      :operations => [{
        :httpMethod => http_method,
        :nickname => nickname,
        :responseClass => response_class,
        :summary => summary,
        :notes => note,
        :parameters => parameters.map{ |parameter| parameter.to_json },
        :errorResponses => error_responses.map{ |error_response| error_response.to_json }
      }]
    }
  end

  private 

  def nickname
    "api_#{id}"
  end

  def sync_doc_id
    self.doc_id = resource.doc_id unless doc_id
  end

end

app/models/doc.rb
class Doc < ActiveRecord::Base

  validates_presence_of :user_id
  validates_presence_of :name
  validates_presence_of :api_version
  validates_presence_of :request_path

  belongs_to :user
  has_many :resources, :dependent => :destroy, :order => "sort ASC"
  has_many :models, :dependent => :destroy
  has_many :doc_users
  has_many :users, :through => :doc_users

  before_create :generate_unique_subdomain

  def version
    api_version
  end

  def to_json
    { 
      :apiVersion => version,
      :swaggerVersion => "1.1",
      :basePath => "http://#{host_to_json}",
      :requestPath => request_path,
      :apis => resources.map{ |resource| { :id => resource.id, :path => "/#{resource.name}.{format}", :description => resource.description } }
    }
  end

  def host_to_json
    fqdn.present? ? fqdn : "#{subdomain}.#{Setting.host}"
  end

  def preview_link
    "http://#{host_to_json}"
  end

  private

  def generate_unique_subdomain
    begin
      rand ||= SecureRandom.hex(3)
    end while !self.class.count(:conditions => ["subdomain = ?", rand]).zero?
    self.subdomain = rand
  end

end

app/models/doc_user.rb
class DocUser < ActiveRecord::Base
  # attr_accessible :title, :body
  validates_uniqueness_of :user_id, :scope => :doc_id
  belongs_to :user, :counter_cache => :cooperated_docs_count
  belongs_to :doc, :counter_cache => :cooperated_users_count
end

app/models/error_response.rb
class ErrorResponse < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :api
  validates_uniqueness_of :code, :scope => [:api_id]

  def to_json
    { :code => code,
      :reason => reason
    }
  end  
end

app/models/model.rb
class Model < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :doc
  has_many :properties, :dependent => :destroy
  accepts_nested_attributes_for :properties, :allow_destroy => true
  validates_uniqueness_of :name, :scope => [:doc_id]
  validates_presence_of :name
  validates_presence_of :doc_id

  def to_json
    hash_properties = {}
    properties.each do |property|
      hash_properties[property.name] = property.to_json
    end
    json = {
      :id => name
    }
    json[:properties] = hash_properties if hash_properties.size > 0
    json
  end
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :api
  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [ :api_id ]
  PARAM_TYPES = [:path, :query, :body, :header]
  DATA_TYPES = [:string, :byte, :boolean, :int, :long, :float, :double, :date, :time, :datetime, :List, :Set, :Array]

  def to_json
    json = {
      :paramType => param_type,
      :name => name,
      :description => description,
      :dataType => data_type,
      :required => required,
      :allowMultiple => allow_multiple
    }
    json[:allowableValues] = {
        :valueType => "LIST",
        :values => allowable_values.gsub(", ", ",").split(",")
    } if allowable_values.present?
    json
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :model
  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:model_id]

  def to_json
    json = {
      :type => data_type
    }
    json[:description] = description if description.present?
    if allowable_values.present?
      json[:allowableValues] = {
          :valueType => "LIST",
          :values => allowable_values.gsub(", ", ",").split(",")
      }
    end
    json
  end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :doc
  has_many :apis, :dependent => :destroy, :order => "sort ASC"
  validates_presence_of :doc_id
  validates_uniqueness_of :name, :scope => [:doc_id]
  include ActsAsSortable

  def to_json
    models_json = {}
    doc.models.each do |model|
      models_json[model.name] = model.to_json
    end
    {
      :id => id,
      :apiVersion => doc.version,
      :swaggerVersion => "1.1",
      :apis => apis.map{ |api| api.to_json },
      :models => models_json
    }
  end

end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/setting.yml"
  namespace Rails.env

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable, :recoverable
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :docs
  has_many :doc_users
  has_many :cooperated_docs, :through => :doc_users, :source => :doc

  def self.create_by_omniauth(hash, current_user)
    hash = ActiveSupport::HashWithIndifferentAccess.new hash
    user = User.send("find_by_#{hash[:provider]}_id", hash[:uid])
    unless user
      user = current_user || User.find_by_email(hash[:info][:email]) || User.new( :email => hash[:info][:email], :name => hash[:info][:name] )
      user.send("#{hash[:provider]}_id=", hash[:uid])
      user.save!
    end
    user
  end
  
  def password_required?
    return false if facebook_id
    true
  end

  def owned?(doc)
    doc.user_id == id
  end
end

app/controllers/admin/models_controller.rb
class Admin::ModelsController < Admin::BaseController
  before_filter :clean_nested_attributes
  before_filter :authenticate_and_find_doc!
  before_filter :get_model, :except => [:index]
  before_filter{ breadcrumb_model(@model) }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @model.save
      redirect_to(params[:redirect_to] || admin_doc_models_path(@doc), :notice => "create success")
    else
      flash[:error] = @model.errors.full_messages
      render :new
    end
  end

  def update
    @model.send params[:sort] if params[:sort]
    if @model.update_attributes params[:model]
      redirect_to(params[:redirect_to] || admin_doc_models_path(@doc), :notice => "update success")
    else
      flash[:error] = @model.errors.full_messages
      render :edit
    end
  end

  def destroy
    @model.destroy
    redirect_to admin_doc_models_path(@doc), :notice => "delete success"
  end

  private

  def get_model
    @model = params[:id] ? @doc.models.find(params[:id]) : @doc.models.new(params[:model])
  end

  def clean_nested_attributes
    return unless params[:model]
    { :properties => :name }.each do |nested_name, check_field|
      key = "#{nested_name}_attributes"
      next unless params[:model][key]
      params[:model][key] = params[:model][key].select do |k, values|
        values[check_field].present?
      end
    end
  end
end

app/views/admin/models/_form.html.haml
- model = form.object
.form-inputs
  = form.input :name, :placeholder => "Product"
  = form.input :description
  .control-group
    %label.control-label= "Properties"
    .controls
      = render :partial => "nested_properties", :object => form, :as => :form
.form-actions
  = form.submit :class => "btn btn-primary"
  = link_to "Cancel", request.env["HTTP_REFERER"] || admin_doc_models_path(model.doc), :class => "btn"
= hidden_input_redirect_to

app/views/admin/models/_list.html.haml
%table.table.table-hover
  %thead
    %tr
      %th="#"
      %th="name"
      %th="description"
      %th.last=""
  %tbody
    - models.each do |model|
      %tr
        %td= model.id
        %td= model.name
        %td= model.description
        %td.last
          = link_to edit_admin_doc_model_path(model.doc, model), :class => "btn btn-mini" do
            %i.icon.icon-pencil
            Edit
          - if can?(:destroy, model)
            = link_to admin_doc_model_path(model.doc, model), :class => "btn btn-mini btn-danger", :method => :delete, :confirm => "confirm delete?" do
              %i.icon-white.icon-remove
              Delete

app/views/admin/models/_nested_properties.html.haml
= form.link_to_add :properties, :class => "btn btn-mini", :data => { :target => "#form_property" } do
  %i.icon-plus
  Add Property
#form_property
  = form.fields_for :properties do |form_property|
    .form-inline
      = form_property.link_to_remove :class => "btn btn-mini" do
        %i.icon-minus
        Delete
      = form_property.input_field :name, :placeholder => :name, :class => "input-small"
      = form_property.input_field :description, :placeholder => :description, :class => "input-medium"
      = render_data_type_form(form_property, @doc)
      = form_property.input_field :allowable_values, :placeholder => "allow values", :class => "input-medium", :as => :string

app/views/admin/models/edit.html.haml
%h1= "Edit Model ##{@model.name}"
= simple_nested_form_for @model, :url => admin_doc_model_path(@doc, @model), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :object => f

app/views/admin/models/index.html.haml
= render :partial => "admin/docs/info", :object => @doc, :as => :doc

%h2="Model list"
= link_to_create "Create Model", new_admin_doc_model_path(@doc)

= render :partial => "list", :object => @doc.models, :as => :models

app/views/admin/models/new.html.haml
%h1= "New Model"
= simple_nested_form_for @model, :url => admin_doc_models_path(@doc), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :object => f