config/routes.rb
SwaggerRails::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure', :as => :auth_failure
  match '/auth/facebook', :as => :facebook_login

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy", :as => :user_logout
  end

  devise_for :users


  constraints(ForeignDomain::Route) do
    root :to => "docs#show"
    get "/:name", :controller => "resources", :action => 'show'
  end
  
  root :to => 'admin/docs#index'

  namespace :admin do
    root :to => "docs#index"
    resources :docs do
      resources :models
      resources :resources do
        resources :apis
      end
    end
  end
end

app/views/admin/resources/_form.html.haml
- resource = form.object
.form-inputs
  = form.input :name, :placeholder => "Products"
  = form.input :description
  = form.input :sort, :hint => "Will be sorted from 1 to 999"
.form-actions
  = form.submit :class => "btn btn-primary"
  = link_to "Cancel", request.env["HTTP_REFERER"] || admin_doc_resources_path(resource.doc), :class => "btn"
= hidden_input_redirect_to

app/views/admin/resources/_info.html.haml
%h1
  = resource.name
  = link_to edit_admin_doc_resource_path(resource.doc, resource), :class => "btn btn-mini" do
    %i.icon-pencil
.doc_info
  %ul
    %li= "description: #{resource.description}" if resource.description.present?

app/views/admin/resources/_list.html.haml
%table.table.table-hover
  %thead
    %tr
      %th="#"
      %th="name"
      %th="sort"
      %th.last=""
  %tbody
    - resources.each do |resource|
      %tr
        %td= resource.id
        %td= link_to resource.name, admin_doc_resource_path(resource.doc, resource)
        %td
          = render :partial => "sort_buttons", :as => :button_urls, :object => resource_button_urls(resource)
        %td.last
          = link_to edit_admin_doc_resource_path(resource.doc, resource), :class => "btn btn-mini" do
            %i.icon-pencil
            Edit
          - if can?(:destroy, resource)
            = link_to admin_doc_resource_path(resource.doc, resource), :class => "btn btn-mini btn-danger", :method => :delete, :confirm => "confirm delete?" do
              %i.icon-white.icon-remove
              Delete

app/views/admin/resources/edit.html.haml
%h1= "Edit Resource ##{@resource.name}"
= simple_form_for @resource, :url => admin_doc_resource_path(@doc, @resource), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :object => f

app/views/admin/resources/index.html.haml
= render :partial => "admin/docs/info", :object => @doc, :as => :doc

%h2= "Resources"

= link_to_create "Create Resource", new_admin_doc_resource_path(@doc)

= render :partial => "list", :object => @doc.resources, :as => :resources

app/views/admin/resources/new.html.haml
%h1= "New Resource"
= simple_form_for @resource, :url => admin_doc_resources_path(@doc), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :object => f

app/views/admin/resources/show.html.haml
= render :partial => "admin/docs/info", :object => @doc, :as => :doc
= render :partial => "admin/resources/info", :object => @resource, :as => :resource

%h2= "Apis List"
= link_to "Create Api", new_admin_doc_resource_api_path(@doc, @resource), :class => "btn btn-primary"    

%table.table.table-hover
  %thead
    %tr
      %th="#"
      %th="Path"
      %th="Sort"
      %th.last=""
  %tbody
    - @resource.apis.each do |api|
      %tr
        %td= api.id
        %td
          = api.http_method
          &nbsp;
          = api.path
        %td
          = render :partial => "sort_buttons", :as => :button_urls, :object => api_button_urls(api)
        %td.last
          = link_to edit_admin_doc_resource_api_path(@doc, @resource, api), :class => "btn btn-mini" do
            %i.icon.icon-pencil
            Edit
          - if can?(:destroy, api)
            = link_to admin_doc_resource_api_path(@doc, @resource, api), :class => "btn btn-mini btn-danger", :method => :delete, :confirm => "confirm delete?" do
              %i.icon-white.icon-remove
              Delete