config/routes.rb
SwaggerRails::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure', :as => :auth_failure
  match '/auth/facebook', :as => :facebook_login

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy", :as => :user_logout
  end

  devise_for :users


  constraints(ForeignDomain::Route) do
    root :to => "docs#show"
    get "/:name", :controller => "resources", :action => 'show'
  end
  
  root :to => 'admin/docs#index'

  namespace :admin do
    root :to => "docs#index"
    resources :docs do
      resources :models
      resources :resources do
        resources :apis
      end
    end
  end
end

app/models/doc.rb
class Doc < ActiveRecord::Base

  validates_presence_of :user_id
  validates_presence_of :name
  validates_presence_of :api_version
  validates_presence_of :request_path

  belongs_to :user
  has_many :resources, :dependent => :destroy, :order => "sort ASC"
  has_many :models, :dependent => :destroy
  has_many :doc_users
  has_many :users, :through => :doc_users

  before_create :generate_unique_subdomain

  def version
    api_version
  end

  def to_json
    { 
      :apiVersion => version,
      :swaggerVersion => "1.1",
      :basePath => "http://#{host_to_json}",
      :requestPath => request_path,
      :apis => resources.map{ |resource| { :id => resource.id, :path => "/#{resource.name}.{format}", :description => resource.description } }
    }
  end

  def host_to_json
    fqdn.present? ? fqdn : "#{subdomain}.#{Setting.host}"
  end

  def preview_link
    "http://#{host_to_json}"
  end

  private

  def generate_unique_subdomain
    begin
      rand ||= SecureRandom.hex(3)
    end while !self.class.count(:conditions => ["subdomain = ?", rand]).zero?
    self.subdomain = rand
  end

end

app/controllers/admin/docs_controller.rb
class Admin::DocsController < Admin::BaseController
  before_filter :authenticate_and_find_doc!, :except => [:index]
  before_filter{ breadcrumb_doc(@doc) }

  def index
    @docs = current_user.docs
    @cooperated_docs = current_user.cooperated_docs
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @doc.save
      redirect_to(params[:redirect_to] || admin_doc_path(@doc), :notice => "create success")
    else
      flash[:error] = @doc.errors.full_messages
      render :new
    end
  end

  def update
    if @doc.update_attributes params[:doc]
      redirect_to(params[:redirect_to] || admin_doc_path(@doc), :notice => "update success")
    else
      flash[:error] = @doc.errors.full_messages
      render :edit
    end
  end

  def destroy
    @doc.destroy
    redirect_to admin_docs_path, :notice => "delete success"
  end

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  
  include ForeignDomain::Base

  def show
    respond_to do |f|
      f.html { render :layout => false}
      f.json { render :json => @doc.to_json }
    end
  end
end

app/views/admin/docs/_cooperated_docs.html.erb
<h1>Cooperated Doc list</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>name</th>
      <th>description</th>
      <th>version</th>
      <th class="last"></th>
    </tr>
  </thead>
  <tbody>
    <% docs.each do |doc| %>
      <tr>
        <td><%= doc.id %></td>
        <td><%= link_to doc.name, admin_doc_path(doc) %></td>
        <td><%= truncate(doc.description, :length => 30) %></td>
        <td><%= doc.version %></td>
        <td class="last">
          <%= link_to edit_admin_doc_path(doc), :class => "btn btn-mini" do %>
            <i class="icon icon-pencil"></i>
            Edit
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/docs/_form.html.haml
.form-inputs
  = form.input :name, :placeholder => "Page title"
  = form.input :api_version, :placeholder => "1.1.2", :hint => "Your API version"
  = form.input :request_path, :placeholder => "http://staging.api.exmaple.com", :hint => "URL for Try it out"
  = form.input :api_key_name, :placeholder => "access_token", :hint => "API token key for Try it out"
  = form.input :api_key, :placeholder => "1234", :hint => "API token for Try it out"
  = form.input :caption, :hint => "Title text above description"
  = form.input :description
  = form.input :fqdn, :placeholder => "api.example.com", :hint => "Your foreign domain to link this API doc page"
  - if current_user.owned?(form.object)
    = form.input :user_ids, :as => :select, :input_html => { :class => :chosen, :multiple => :true }, :label => "Users for cooperation", :collection => current_user_friends_collection
.form-actions
  = form.submit :class => "btn btn-primary"
  = link_to "Cancel", request.env["HTTP_REFERER"] || admin_docs, :class => "btn"
= hidden_input_redirect_to

app/views/admin/docs/_info.html.haml
%h1
  = doc.name
  = link_to edit_admin_doc_path(doc), :class => "btn btn-mini" do
    %i.icon-pencil
.doc_info
  %ul
    %li
      = "Preview: "
      = link_to(doc.preview_link, doc.preview_link)
    - if doc.description.present?
      %li= "description: #{doc.description}"
    %li= "version: #{doc.version}"
    - if doc.request_path.present?
      %li= "API testing url format: #{doc.request_path}/{API Path}.json?#{doc.api_key_name}=#{doc.api_key}"

app/views/admin/docs/edit.html.haml
%h1= "Edit Doc ##{@doc.id} #{@doc.name}"
= simple_form_for @doc, :url => admin_doc_path(@doc), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :object => f

app/views/admin/docs/index.html.haml
%h1="My Doc list"
= link_to_create "Create Doc", new_admin_doc_path

%table.table.table-hover
  %thead
    %tr
      %th="#"
      %th="name"
      %th="description"
      %th="version"
      %th.last=""
  %tbody
    - @docs.each do |doc|
      %tr
        %td= doc.id
        %td= link_to doc.name, admin_doc_path(doc)
        %td= truncate(doc.description, :length => 30)
        %td= doc.version
        %td.last
          = link_to edit_admin_doc_path(doc), :class => "btn btn-mini" do
            %i.icon.icon-pencil
            Edit
          = link_to admin_doc_path(doc), :class => "btn btn-mini btn-danger", :method => :delete, :confirm => "confirm delete?" do
            %i.icon-white.icon-remove
            Delete

= render :partial => "cooperated_docs", :as => :docs, :object => @cooperated_docs

app/views/admin/docs/new.html.haml
%h1= "New Doc"
= simple_form_for @doc, :url => admin_docs_path, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :object => f

app/views/admin/docs/show.html.haml
= render :partial => "info", :object => @doc, :as => :doc
  
%h2= "Resources List"
= link_to_create "Create Resource", new_admin_doc_resource_path(@doc)
= render :partial => "admin/resources/list", :as => :resources, :object => @doc.resources.limit(5)
= link_to_more_resources @doc, 5

%h2= "Models List"
= link_to_create "Create Model", new_admin_doc_model_path(@doc)
= render :partial => "admin/models/list", :as => :models, :object => @doc.models.limit(5)
= link_to_more_models @doc, 5