config/routes.rb
SwaggerRails::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure', :as => :auth_failure
  match '/auth/facebook', :as => :facebook_login

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy", :as => :user_logout
  end

  devise_for :users


  constraints(ForeignDomain::Route) do
    root :to => "docs#show"
    get "/:name", :controller => "resources", :action => 'show'
  end
  
  root :to => 'admin/docs#index'

  namespace :admin do
    root :to => "docs#index"
    resources :docs do
      resources :models
      resources :resources do
        resources :apis
      end
    end
  end
end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <ul class="nav nav-pills pull-right">
    <li></li>
  </ul>
  <p class="copyright">Copyright @2012 <%= Setting.app_name %> All rights reserved.</p>

</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-fixed-top ">
  <div class="navbar-inner top ">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to(Setting.app_name, root_path , :class => "brand" )%>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to("Docs",admin_docs_path) %></li>
        </ul>  
        <%= render :partial => "common/user_nav"%>
      </div>
    </div>
  </div>

  <%= yield :submenu %>

</div>

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">

    <li>
      <div class="social"></div>
    </li>

  <% if current_user %>    

    <li class="dropdown">
      <%= link_to "#" , :class => "dropdown-toggle", :data => { :toogle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>

      <ul class="dropdown-menu">
        <li><%= link_to("Logout",destroy_user_session_path, :method => :delete ) %></li>
      </ul>
    </li>

<% else %>
  <li> <%= link_to( "Login", new_user_session_path )  %> </li>   
<% end %>


</ul>